<!DOCTYPE html>
<html lang="en">

  <head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Markdown</title>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/simplemde/latest/simplemde.min.css">
    <script src="https://cdn.jsdelivr.net/simplemde/latest/simplemde.min.js"></script>
  </head>

  <body>
    <h3>Markdown Editor</h3>
    <form method="post" action="/markdown/new">
      New File:<br>
      <input type="text" name="file" autocomplete="off" /><br>
      Content:<br>
      <textarea id="markdown" col="66" rows="15" name="content"></textarea><br>
      <button type="submit" name="save-file">Submit</button>






    </form>

    <script>
    let simplemde = new SimpleMDE({
      element: document.getElementById("markdown")
    });
    simplemde.value("This text will appear in the editor");
    </script>
  </body>

</html>