<!DOCTYPE html>
<html lang="<?= $scLanguage ?>" dir="ltr" color-scheme="auto">

  <head>
    <meta charset="<?= $scCharset ?>">
    <meta name="robots" content="noindex">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">


    <title><?= $scTitle . " | " . $scSiteName ?></title>

    <!-- Style link to fontawesome 4 -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.0/css/all.min.css"
      integrity="sha512-xh6O/CkQoPOWDdYTDqeRdPCVd1SpvCA9XXcUnZS2FmJNp1coAFzvtCN9BmamE+4aHK8yyUHUSCcJHgXloTyT2A=="
      crossorigin="anonymous" referrerpolicy="no-referrer" />

    <link rel="stylesheet" href="/css/<?= $scPath ?>.css">
  </head>

  <body>
