<main id="login">


  <?php if (!empty($data['errorList'])) : ?>
  <div>
    <p>Errors:</p>
    <ul>
      <?php foreach ($data['errorList'] as $value) : ?>
      <li><?= $value ?></li>
      <?php endforeach ?>
    </ul>
  </div>
  <?php endif ?>



  <form class="formContainer" action="/Admin/Login/create" method="post">
    <label class="email" for="email">E-mail
      <input type="email" name="email" id="email" placeholder="Your Email" autofocus required>
    </label>
    <label class="password" for="password">Password
      <input type="password" name="password" id="password" placeholder="Your Password" required>
    </label>
    <input class="submit" type="submit" value="SEND">
  </form>
</main>
