    <footer>
      <p><?php echo $scMetaCopyright; ?></p>
      <p>powered by <span class="scorpio">Quickstart</span> created by
        <span class="scorpio">
          <a href="https://scorpiocoding.com">ScorpioCoding.com</a>
        </span>
      </p>
    </footer>
    <script src="/js/site/navigation.js" defer></script>
    <script src="/js/<?php echo $scMetaPath; ?>.js" defer></script>
    </body>

    </html>